In [2]:
import os

os.environ["TF_CPP_MIN_LOG_LEVEL"] = "3"
os.environ["ENV TF_ENABLE_ONEDNN_OPTS"] = "1"

import tensorflow as tf
from tensorflow.keras.layers import *
import numpy as np
import math


f_dct = lambda x: tf.signal.dct(x, n=16)
x = np.random.rand(32)
y = f_dct(x)
y

<tf.Tensor: shape=(16,), dtype=float64, numpy=
array([12.44572842, -1.4671513 ,  1.11915102,  3.97395516, -0.47949095,
        1.8693353 ,  0.80340229, -0.42496952, -0.19779324, -3.05811889,
       -0.7872147 , -0.13967748,  0.15165718, -1.37268262, -1.3585825 ,
        0.20922853])>

In [4]:
x2 = [Lambda(lambda z: z[0][:, -(2 ** z[1]) :])((x1, i)) for i in range(n)]
x3 = [Lambda(lambda z: z[:, -(2 ** i) :])(x1) for i in range(n)]
print(x2, x3)


[<tf.Tensor: shape=(4, 1), dtype=float32, numpy=
 array([[0.299],
        [0.451],
        [0.214],
        [0.309]], dtype=float32)>,
 <tf.Tensor: shape=(4, 2), dtype=float32, numpy=
 array([[0.973, 0.299],
        [0.327, 0.451],
        [0.251, 0.214],
        [0.478, 0.309]], dtype=float32)>,
 <tf.Tensor: shape=(4, 4), dtype=float32, numpy=
 array([[0.03 , 0.094, 0.973, 0.299],
        [0.198, 0.456, 0.327, 0.451],
        [0.24 , 0.879, 0.251, 0.214],
        [0.616, 0.41 , 0.478, 0.309]], dtype=float32)>,
 <tf.Tensor: shape=(4, 8), dtype=float32, numpy=
 array([[0.538, 0.005, 0.937, 0.334, 0.03 , 0.094, 0.973, 0.299],
        [0.602, 0.573, 0.387, 0.373, 0.198, 0.456, 0.327, 0.451],
        [0.216, 0.191, 0.132, 0.961, 0.24 , 0.879, 0.251, 0.214],
        [0.056, 0.438, 0.986, 0.81 , 0.616, 0.41 , 0.478, 0.309]],
       dtype=float32)>]

In [5]:
# moments = [Lambda(lambda z: tf.nn.moments(z, axes=[1], keepdims=False)[1])(x2[i]) for i in range(n)]
means = [Lambda(lambda z: tf.math.reduce_mean(z,1, keepdims=True))(x2[i]) for i in range(n)]
stds = [Lambda(lambda z: tf.math.reduce_std(z,1, keepdims=True))(x2[i]) for i in range(n)]
R = [Lambda(lambda z: tf.math.reduce_max(z,1, keepdims=True)-tf.math.reduce_min(z,1, keepdims=True))(x2[i]) for i in range(n)]
print(R)
Concatenate(1)(means)

[<tf.Tensor: shape=(4, 1), dtype=float32, numpy=
array([[0.],
       [0.],
       [0.],
       [0.]], dtype=float32)>, <tf.Tensor: shape=(4, 1), dtype=float32, numpy=
array([[0.31099996],
       [0.139     ],
       [0.07499999],
       [0.91300005]], dtype=float32)>, <tf.Tensor: shape=(4, 1), dtype=float32, numpy=
array([[0.579     ],
       [0.37      ],
       [0.602     ],
       [0.91300005]], dtype=float32)>, <tf.Tensor: shape=(4, 1), dtype=float32, numpy=
array([[0.643     ],
       [0.666     ],
       [0.65      ],
       [0.91300005]], dtype=float32)>]


<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[0.641     , 0.48549998, 0.288     , 0.40574998],
       [0.847     , 0.77750003, 0.62975   , 0.518625  ],
       [0.788     , 0.75049996, 0.52125   , 0.44612503],
       [0.975     , 0.51850003, 0.48575002, 0.444875  ]], dtype=float32)>

In [1]:
import tensorflow as tf
import numpy as np
a = np.arange(8, dtype="float32").reshape(2,4)
c = np.ones((2,3,4), dtype="float32")
x = tf.reshape(a, (a.shape[0], 1, a.shape[1]))
x = tf.tile(x,[1,3,1])
x = tf.subtract(x, c)
x = tf.multiply(x, x)

In [2]:
x = -tf.reduce_sum(x, 2)
x

<tf.Tensor: shape=(2, 3), dtype=float32, numpy=
array([[ -6.,  -6.,  -6.],
       [-86., -86., -86.]], dtype=float32)>