In [16]:
import tensorflow as tf
import numpy as np

y = tf.constant([[[1, 2, 3, 4, 5],[-1,-2,-3,-4, -5]]], dtype='float32')*40
s = tf.math.softsign(y)
s.numpy()


array([[[ 0.9756098 ,  0.9876543 ,  0.9917355 ,  0.99378884,
          0.99502486],
        [-0.9756098 , -0.9876543 , -0.9917355 , -0.99378884,
         -0.99502486]]], dtype=float32)

In [1]:
import tensorflow as tf
from tensorflow.keras.layers import *
import numpy as np
import math

sample_width = 1
input_width = 8
sections = int(math.log2(input_width))
n = sections + 1
y = np.tile(np.arange(input_width, dtype='float32').reshape(1,8,1),(4,1,1))
x = [Lambda(lambda z: z[:, -(2 ** i) :, :])(y) for i in range(n)]
x = [AveragePooling1D(pool_size=2 ** i, strides=1)(x[i]) for i in range(n)]
x = Concatenate(axis=1)(x)
x = Flatten()(x)
x = Dense(4, "softsign")(x)
x

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[ 0.6661075 , -0.94669586, -0.77445054,  0.7149933 ],
       [ 0.6661075 , -0.94669586, -0.77445054,  0.7149933 ],
       [ 0.6661075 , -0.94669586, -0.77445054,  0.7149933 ],
       [ 0.6661075 , -0.94669586, -0.77445054,  0.7149933 ]],
      dtype=float32)>