In [8]:
import tensorflow as tf
from tensorflow.keras.layers import *
import numpy as np
import math

sample_width = 1
input_width = 8
sections = int(math.log2(input_width))
n = sections + 1
# x1 = np.tile(np.random.random(input_width*4).reshape(8),(4,1)).astype("float32").round(3)
x1 = np.random.random(input_width*4).reshape(4,input_width).astype("float32").round(3)

In [9]:
x2 = [Lambda(lambda z: z[0][:, -(2 ** z[1]) :])((x1, i)) for i in range(n)]
x2

[<tf.Tensor: shape=(4, 1), dtype=float32, numpy=
 array([[0.012],
        [0.725],
        [0.931],
        [0.345]], dtype=float32)>,
 <tf.Tensor: shape=(4, 2), dtype=float32, numpy=
 array([[0.259, 0.012],
        [0.493, 0.725],
        [0.541, 0.931],
        [0.475, 0.345]], dtype=float32)>,
 <tf.Tensor: shape=(4, 4), dtype=float32, numpy=
 array([[0.403, 0.877, 0.259, 0.012],
        [0.096, 0.909, 0.493, 0.725],
        [0.227, 0.997, 0.541, 0.931],
        [0.921, 0.006, 0.475, 0.345]], dtype=float32)>,
 <tf.Tensor: shape=(4, 8), dtype=float32, numpy=
 array([[0.099, 0.898, 0.09 , 0.431, 0.403, 0.877, 0.259, 0.012],
        [0.003, 0.877, 0.8  , 0.784, 0.096, 0.909, 0.493, 0.725],
        [0.155, 0.625, 0.444, 0.351, 0.227, 0.997, 0.541, 0.931],
        [0.211, 0.964, 0.639, 0.353, 0.921, 0.006, 0.475, 0.345]],
       dtype=float32)>]

In [24]:
# moments = [Lambda(lambda z: tf.nn.moments(z, axes=[1], keepdims=False)[1])(x2[i]) for i in range(n)]
means = [Lambda(lambda z: tf.math.reduce_mean(z,1, keepdims=True))(x2[i]) for i in range(n)]
stds = [Lambda(lambda z: tf.math.reduce_std(z,1, keepdims=True))(x2[i]) for i in range(n)]
print(means)
Concatenate(1)(means)

[<tf.Tensor: shape=(4, 1), dtype=float32, numpy=
array([[0.012],
       [0.725],
       [0.931],
       [0.345]], dtype=float32)>, <tf.Tensor: shape=(4, 1), dtype=float32, numpy=
array([[0.1355],
       [0.609 ],
       [0.736 ],
       [0.41  ]], dtype=float32)>, <tf.Tensor: shape=(4, 1), dtype=float32, numpy=
array([[0.38775],
       [0.55575],
       [0.674  ],
       [0.43675]], dtype=float32)>, <tf.Tensor: shape=(4, 1), dtype=float32, numpy=
array([[0.38362497],
       [0.58587503],
       [0.533875  ],
       [0.48924997]], dtype=float32)>]


<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[0.012     , 0.1355    , 0.38775   , 0.38362497],
       [0.725     , 0.609     , 0.55575   , 0.58587503],
       [0.931     , 0.736     , 0.674     , 0.533875  ],
       [0.345     , 0.41      , 0.43675   , 0.48924997]], dtype=float32)>